# Generated by Django 5.0.3 on 2024-03-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
