# Generated by Django 5.0.3 on 2024-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
