# Generated by Django 5.0.3 on 2024-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime', '0006_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
