# Generated by Django 5.0.3 on 2024-03-06 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime', '0007_otp_pan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='pan_number',
        ),
        migrations.CreateModel(
            name='PAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pans', to='ontime.otp')),
            ],
        ),
    ]
