# Generated by Django 5.0.3 on 2024-03-09 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime', '0008_remove_otp_pan_number_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADHAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_number', models.IntegerField(unique=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhar', to='ontime.otp')),
            ],
        ),
        migrations.CreateModel(
            name='BANK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(unique=True)),
                ('ifsc', models.CharField(max_length=20)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='ontime.otp')),
            ],
        ),
    ]
