# Generated by Django 5.0.3 on 2024-03-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontime', '0009_adhar_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOCUMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_slip', models.FileField(upload_to='documents/')),
                ('bank_statement', models.FileField(upload_to='documents/')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='ontime.otp')),
            ],
        ),
    ]
